version: '3.8'
services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "127.0.0.1::3000"
    restart: always
    depends_on:
      - redis
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_URI=YOUR_MONGO_URI

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "127.0.0.1::6379"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/prod:/etc/nginx/conf.d
    restart: always
    ports:
      - "80:80"
      - "443:443"