version: '3.8'
services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    restart: always
    links:
      - redis
    depends_on:
      - redis
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_URI=YOUR_MONGO_URI

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/dev:/etc/nginx/conf.d
    restart: always
    ports:
      - "80:80"

